export const SIGNUP_PHONE_IDLE = 'SIGNUP_PHONE_IDLE'
export const SIGNUP_PHONE_REQUEST = 'SIGNUP_PHONE_REQUEST'
export const SIGNUP_PHONE_SUCCESS = 'SIGNUP_PHONE_SUCCESS'
export const SIGNUP_PHONE_FAILURE = 'SIGNUP_PHONE_FAILURE'

export const SIGNUP_EMAIL_IDLE = 'SIGNUP_EMAIL_IDLE'
export const SIGNUP_EMAIL_REQUEST = 'SIGNUP_EMAIL_REQUEST'
export const SIGNUP_EMAIL_SUCCESS = 'SIGNUP_EMAIL_SUCCESS'
export const SIGNUP_EMAIL_FAILURE = 'SIGNUP_EMAIL_FAILURE'

export const SIGNUP_PASSWORD_IDLE = 'SIGNUP_PASSWORD_IDLE'
export const SIGNUP_PASSWORD_REQUEST = 'SIGNUP_PASSWORD_REQUEST'
export const SIGNUP_PASSWORD_SUCCESS = 'SIGNUP_PASSWORD_SUCCESS'
export const SIGNUP_PASSWORD_FAILURE = 'SIGNUP_PASSWORD_FAILURE'