/**
 *
 */
export const DATING_SEARCH_REQUEST = 'DATING_SEARCH_REQUEST';
export const DATING_SEARCH_SUCCESS = 'DATING_SEARCH_SUCCESS';

/**
 *
 */
export const DATING_MATCHED_REQUEST = 'DATING_MATCHED_REQUEST';
export const DATING_MATCHED_SUCCESS = 'DATING_MATCHED_SUCCESS';
