export const DATING_GET_IDLE    = 'DATING_GET_IDLE'
export const DATING_GET_REQUEST = 'DATING_GET_REQUEST'
export const DATING_GET_SUCCESS = 'DATING_GET_SUCCESS'
export const DATING_GET_FAILURE = 'DATING_GET_FAILURE'
