export const DATING_GET_PARTNERS = 'DATING_GET_PARTNERS'
export const DATING_GET_PARTNERS_REQUEST = 'DATING_GET_PARTNERS_REQUEST'
export const DATING_GET_PARTNERS_SUCCESS = 'DATING_GET_PARTNERS_SUCCESS'
export const DATING_GET_PARTNERS_FAILURE = 'DATING_GET_PARTNERS_FAILURE'
