name: CI
on: [workflow_dispatch]
defaults:
  run:
    working-directory: ios
jobs:
  build:
    runs-on: [self-hosted, macOS, X64]
    steps:
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2.1.4
  
    - name: Setup dependencies
      run: install --network-timeout 1000000

    - name: Install react native
      run: |
        sudo npm install -g react-native-cli

    - name: Install fastlane
      run: |
        sudo gem install fastlane

    - name: Build
      env:
        MATCH_TYPE: ${{ secrets.MATCH_TYPE }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        APP_SCHEME: ${{ secrets.APP_SCHEME }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        MATCH_APP_IDENTIFIER: ${{ secrets.MATCH_APP_IDENTIFIER }}
        FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
        MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
        FASTLANE_SESSION: ${{ secrets.MATCH_USERNAME }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      run: |
        TAG=$(echo ${GITHUB_REF}| cut -d'-' -f 3)
        export BUILD_NUM=$(echo $TAG| cut -d'b' -f 2)
        export VERSION_NUM=$(echo $TAG| cut -d'b' -f 3)
        pod install --repo-update
        fastlane beta --env development --verbose
